name: build

on:
  push:
  schedule:
    - cron:  '*/7 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libopencv-dev libgphoto2-dev
    - name: Install Qt
      uses: ouuan/install-qt-action@v2.3.1
    - name: Build
      run: sh ./scripts/build_linux.sh
    - name: Test
      run: cd build/Release && ctest --output-on-failure
